### ISSUE TITLE
Predictive algorithm

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/Keyboard#4]

**Comment by lopezjuanma96** [comment]
![diagram](https://user-images.githubusercontent.com/48799361/173859760-60348d7a-469c-47e2-a944-b4f9dfbc15a7.png)

This is the current pipeline for the predictive algorithm

**Comment by lopezjuanma96** [comment]
@asimjawad will create a method that sends the current typed text to a function after a space key is pressed. this function will serve as a placeholder for the final prediciton method, but for now it can maybe to a simulation with ifs: if the text is "hola" let the predictions be "como estas" "mi nombre es" and "amigo" and if the text is "quiero" let the predictions be "agua" "comer", "asado". Then this pseudo-predictions can be shown on the keyboard GUI.

@lopezjuanma96 will find a way to implement the logic inside the keyboard, for now the options are: cloud funciton (can be slow if the server gets to sleep, or expensive to keep it awake), pyhton wrap or as a last choice doing some attempt at writting in Flutter/Dart and then let Asim polish it.

**Comment by lopezjuanma96** [comment]
A first version of the Cloud Function is already running on Firebase with a test model. A deeper reference can be found on PictogramsPredictionsLibrary#29, but briefly for @asimjawad :

- to add a sentence for the model to train on, do a POST request to the URL https://us-central1-questions-abd23.cloudfunctions.net/viterbi/learn with the body:

{
"sentence": "me gusta el helado",
"userName": "user",
"model": "test"
"language": "es"
}

This will return an array with a report of the process.

- to predict on a sentence with the model, do a POST request to the URL https://us-central1-questions-abd23.cloudfunctions.net/viterbi/predict with the body:

{
"sentence": "yo quiero ir a",
"userName": "user",
"model": "test"
"language": "es"
}

This will return a JSON with the predictions as keys and probabilities as values. If there's context data then the value will be an array with the word probability and the context score, if not, the value will be only a Number (float/double) of the transition probability.

Obviously since it's a test model, predictions won't be as good as with the local ones, and it may take a while the first time a certain request is call.
